[build-system]
requires = ["poetry==1.3.2"]
build-backend = "poetry.masonry.api"

[tool.poetry.plugins."nornir.plugins.runners"]
"serial" = "nornir.plugins.runners:SerialRunner"
"threaded" = "nornir.plugins.runners:ThreadedRunner"

[tool.poetry.plugins."nornir.plugins.inventory"]
"SimpleInventory" = "nornir.plugins.inventory.simple:SimpleInventory"

[tool.poetry]
name = "nornir"
version = "3.3.0"
description = "Pluggable multi-threaded framework with inventory management to help operate collections of devices"
authors = ["David Barroso <dbarrosop@dravetech.com>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/nornir-automation/nornir"
classifiers = [
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
"ruamel.yaml" = ">=0.17"
# importlib.metadata has an API change in 3.10 and is no longer provisional
importlib-metadata = { version = "^4", python = "<3.10" }

#### Extras (docs)
# The following dependencies are used for docs generation when installed as extras
# (e.g. pip install nornir[docs])
sphinx = { version = "^4", optional = true }
sphinx_rtd_theme = { version = "^1.0", optional = true }
sphinxcontrib-napoleon = { version = "^0.7", optional = true }
jupyter = { version = "^1", optional = true }
nbsphinx = { version = "^0.8", optional = true }
pygments = { version = "^2", optional = true }
sphinx-issues = { version = "^3.0", optional = true }

[tool.poetry.group.dev.dependencies]
decorator = "*"
nbval = "*"
pytest = "*"
pytest-cov = "*"
pylama = "*"
requests-mock = "*"
black = "^22.1.0"
mypy = "*"
types-Jinja2 = "^2.11.2"
types-pkg-resources = "^0.1.3"
mypy_extensions = "^0.4.1"
typing_extensions = "^4.1"
nornir-jinja2 = "0.2.0"
nornir-utils = "0.2.0"
nornir-napalm = "0.3.0"

[tool.poetry.extras]
# The following section is required to install docs dependencies
# until RTD fully supports poetry: https://github.com/rtfd/readthedocs.org/issues/4912
docs = ["sphinx", "sphinx_rtd_theme", "sphinxcontrib-napoleon", "jupyter", "nbsphinx", "pygments", "sphinx-issues"]

